avatar/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "avatar"
urlpatterns = [
    url(r'^$',                                          views.main,    name="main"),
    url(r'^about/?$',                                   views.about,   name="about"),
    url(r'^i/(?P<id_img>[0-9a-z]+)/(?P<size>[0-9]+)/?$', views.getimg,  name="getimg"),
    url(r'^i/(?P<id_img>[0-9a-z]+)/?$',                  views.getimg,  name="getimg"),
]

dynimg/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "dynimg"
urlpatterns = [
    url(r'^$',                       views.main,    name="main"),    # Start, end
    url(r'^about/?$',                views.about,   name="about"),   # Start, "about/", end
    url(r'^i/(?P<id_img>[0-9]+)/?$', views.getimg,  name="getimg"),  # Start, "i/", one ore more digits (id_img), "/", end
]

leminaw/urls.py
#-*- coding: utf-8 -*-

from django.conf             import settings
from django.conf.urls        import include, url
from django.conf.urls.static import static
from django.contrib          import admin
from perso.views             import create_error_view

urlpatterns = [
    url(r'^admin/',    admin.site.urls),
    url(r'^namegen/',  include("namegen.urls")),
    url(r'^dynimg/',   include("dynimg.urls")),
    url(r'^playel/',   include("playel.urls")),
    url(r'^profs/',    include("profs.urls")),
    url(r'^avatar/',   include("avatar.urls")),
    url(r'^quotes/',   include("quotes.urls")),
    url(r'^register/', include("register.urls")),
    url(r'^blog/',     include("perso.urls")),
    url(r'^',          include("portfolio.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

handler400 = create_error_view(code=400)
handler403 = create_error_view(code=403)
handler404 = create_error_view(code=404)
handler500 = create_error_view(code=500)

perso/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "perso"
urlpatterns = [
    url(r'^$',                                                  views.main,        name='main'),
    url(r'^(?P<pageId>[0-9]+)/?$',                              views.main,        name='main'),
    url(r'^about/?$',                                           views.about,       name='about'),
    url(r'^contact/?$',                                         views.contact,     name='contact'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/?$',                    views.main,        name='main'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/(?P<pageId>[0-9]+)/?$', views.main,        name='main'),
    url(r'^publication/(?P<slug>[-a-zA-Z0-9_]+)/?$',            views.publication, name='publication'),
    url(r'^tag/(?P<slug>[-a-zA-Z0-9_]+)/?$',                    views.tag,         name='tag'),
]

portfolio/urls.py
from django.conf.urls import url
from . import views

app_name = "portfolio"
urlpatterns = [
    url(r'^$',                                     views.main,    name='main'),
    url(r'^contact/?$',                            views.contact, name='contact'),
    url(r'^labs/?$',                               views.labs,    name='labs'),
    url(r'^work/(?P<work_slug>[-a-zA-Z0-9_]+)/?$', views.work,    name='work'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/?$',       views.main,    name='main'),
]

profs/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "profs"
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^contact/?$', views.contact, name='contact'),
    url(r'^modules/?$', views.modules, name='modules'),
    url(r'^module/(?P<semester>[-a-zA-Z0-9_]+)/(?P<subject>[-a-zA-Z0-9_]+)/(?P<teacher>[-a-zA-Z0-9_]+)/?$', views.module, name='module'),
]

quotes/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "quotes"
urlpatterns = [
    url(r'^$',                 views.main, name="main"),
    url(r'^(?P<id>[0-9]+)/?$', views.main, name="main"),
]

portfolio/models.py
from django.db.models import (Model, DateTimeField, SlugField,
    CharField, TextField, BooleanField, ManyToManyField,
    AutoField, PositiveSmallIntegerField)
from sorl.thumbnail import ImageField
from django.db.models.signals import post_init
from django.urls import reverse
from colorthief import ColorThief
from .utils import rgb_to_hex, hex_to_rgb, alpha
from PIL import Image


class Work(Model):
    added     = DateTimeField(auto_now_add=True,                          verbose_name="ajouté")
    modif     = DateTimeField(auto_now=True,                              verbose_name="modifié")
    slug      = SlugField(unique=True,                                    verbose_name="identifiant")
    title     = CharField(max_length=64,                                  verbose_name="titre")
    subtitle  = CharField(max_length=128,            blank=True,          verbose_name="sous-titre")
    cover     = ImageField(                                               verbose_name="couverture")
    cover_w   = PositiveSmallIntegerField(null=True, blank=True,          verbose_name="largeur couverture")
    cover_h   = PositiveSmallIntegerField(null=True, blank=True,          verbose_name="hauteur couverture")
    content   = TextField(                           blank=True,          verbose_name="contenu")
    bck       = BooleanField(default=False,                               verbose_name="arrière-plan")
    pin       = BooleanField(default=False,                               verbose_name="épinglé")
    black_txt = BooleanField(default=False,                               verbose_name="texte noir")
    categ     = ManyToManyField('Category',          blank=True,          verbose_name="catégorie")
    _palette  = CharField(max_length=64,             blank=True,          verbose_name="palette")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('portfolio:work', kwargs={'work_slug': self.slug})
    
    def get_cover_dimensions(self):
        if self.cover_w is None or self.cover_h is None:
            self.cover_w = self.cover.width
            self.cover_h = self.cover.height
            self.save(compute_palette=False, compute_dimensions=False)
        return self.cover_w, self.cover_h

    def get_svg_placeholder(self):
        w, h = self.get_cover_dimensions()
        return ('data:image/svg+xml,'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}"></svg>'
        )
    
    def compute_color_palette(self):
        self.cover.open() # Fixes a bug in file handling due to w/h update
        thumb = Image.open(self.cover).resize((100, 100))
        ct = ColorThief(thumb, is_obj=True)
        try:
            cols = ct.get_palette(3, ignore_black=False, quality=50)
        except Exception: # NoQA
            cols = ((255, 255, 255), (200, 200, 200), (220, 220, 220))
        while len(cols) < 3:
            cols.append(cols[0])
        self._palette = ';'.join([str(rgb_to_hex(col[:3])) for col in cols])
    
    def get_palette(self):
        if not self._palette:
            self.compute_color_palette()
            self.save(compute_palette=False) # To generate color palette
        palette = self._palette.split(';')
        return tuple([hex_to_rgb(hexcode) for hexcode in palette])
    
    def get_css_gradient(self):
        cols = self.get_palette()
        return ('background-image:'
            f'linear-gradient(000deg, {alpha(cols[0], 0.8)}, {alpha(cols[0], 0.2)} 60%),'
            f'linear-gradient(120deg, {alpha(cols[1], 0.8)}, {alpha(cols[1], 0.2)} 60%),'
            f'linear-gradient(240deg, {alpha(cols[2], 0.8)}, {alpha(cols[2], 0.2)} 60%);')
    
    def save(self, compute_palette=True, compute_dimensions=True, *args, **kwargs):
        if compute_palette:
            self.compute_color_palette()
        if compute_dimensions:
            self.get_cover_dimensions()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "réalisation"
        ordering = ['-pin', '-added']

# Needed to fix a hudge performance issue related to S3 storage.
# Work model implements its own logic to access cover dimensions.
post_init.disconnect(ImageField.update_dimension_fields)


class Category(Model):
    id    = AutoField(primary_key=True, verbose_name="numéro")
    name  = CharField(max_length=64,    verbose_name="nom")
    slug  = SlugField(                  verbose_name="identifiant")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('portfolio:main', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = "catégorie"
        ordering = ['id']

portfolio/views.py
from django.shortcuts import render
from django.http      import HttpResponseRedirect, Http404
from portfolio.models import Category, Work


def main(request, cat_slug=None):
    categs = Category.objects.all()
    if cat_slug is None:
        works = Work.objects.all()
        work_cover = works.filter(bck=True).order_by('?').first()
        categ = None
    else:
        try:
            categ = Category.objects.get(slug=cat_slug)
        except Category.DoesNotExist:
            if request.path.endswith('/'):
                # It's possible that the user requested another app without the
                # trailing slash (minaw.net/profs)
                raise Http404()
            else:
                return HttpResponseRedirect(request.get_full_path() + '/')

        works = Work.objects.filter(categ=categ)
        work_cover = (works.filter(bck=True).order_by('?').first()
            or Work.objects.filter(bck=True).order_by('?').first())

    return render(request, "portfolio/main.html", locals())


def work(request, work_slug):
    categs = Category.objects.all()
    work = Work.objects.get(slug=work_slug)
    work_categs = work.categ.all()

    work_cover = (Work.objects.filter(categ__in=work_categs, bck=True).order_by('?').first()
        or Work.objects.filter(bck=True).order_by('?').first())

    try:
        prev_work = Work.get_previous_by_added(work)
    except Work.DoesNotExist:
        prev_work = None
    try:
        next_work = Work.get_next_by_added(work)
    except Work.DoesNotExist:
        next_work = None

    return render(request, "portfolio/work.html", locals())


def static_view(request, template):
    categs = Category.objects.all()
    work_cover = Work.objects.filter(bck=True).order_by('?').first()
    return render(request, template, locals())


def contact(request):
    return static_view(request, "portfolio/contact.html")


def labs(request):
    return static_view(request, "portfolio/labs.html")


# def create_error_view(code):
#     def error_view(request, *args, **kwargs):
#         barItems     = Category.objects.filter(menu=True)
#         moreBarItems = Category.objects.filter(menu=False)
#
#         coverImage = choice(Cover.objects.filter(pin=True))
#
#         response = render(request, "perso/error.html", locals())
#         response.status_code = code
#         return response
#     return error_view

portfolio/templates/portfolio/base.html
{% load staticfiles %}
{% load thumbnail %}

<!doctype html>
<html lang="fr" {% block htmlparams %}{% endblock %}>
  <head>
    <meta charset="utf-8">
    <title>LeMinaw // Renaud Perrin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="le,minaw,leminaw,le_minaw,renaud,perrin,digital,art,tech,computer,photo,3D,2D,numeric,math,programming">
    <meta name="description" content="Thoughts on arts and techniques for the 21st century">

    <link rel="icon"       href="{% static 'portfolio/img/favicon.png' %}"                                           type="image/png"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poiret+One"                                 type="text/css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa"                                  type="text/css"/>
    <link rel="stylesheet" href="{% static 'portfolio/css/main.css' %}"                                              type="text/css"/>

    {% include 'leminaw/analytics.html' %}
  </head>

  <body>
    {% block scripts %}
      <script src="{% static 'portfolio/js/return.js' %}"></script>
    {% endblock scripts %}

    <header>
      <a class="smallnav" onclick="toggleMenu()" title="Menu de navigation"><i class="fa fa-bars"></i></a>
      <a class="{% if not categ %}active{% endif %}" href="{% url 'portfolio:main' %}">réalisations</a>
      {% for baritem in categs %}
        <a class="{% if baritem == categ %}active{% endif %}" href="{{ baritem.get_absolute_url }}">{{ baritem.name }}</a>
      {% endfor %}
    </header>

    <div class="background">
      {% thumbnail work_cover.cover "300x300" crop="noop" as thumb %}
        <img src="{{ thumb.url }}" alt="{{ work_cover.name }}">
      {% endthumbnail %}
    </div>

    {% block content %}{% endblock %}

    <footer class="{% if not work_cover.black_txt %}white{% endif %}">
      <div><span>Programmed and designed by LeMinaw.</span></div>
      <div><span>
        <a href="{% url 'perso:main' %}">Blog</a>
        |
        <a href="{% url 'portfolio:labs' %}">Labs</a>
        |
        <a href="{% url 'portfolio:contact' %}">Contact</a>
      </span></div>
    </footer>
  </body>
</html>

portfolio/templates/portfolio/contact.html
{% extends "portfolio/base.html" %}

{% block content %}
  <div class="content work">
    <h2>Contact</h2>
    <p>For any remark or question on minaw.net, feel free to send an email to <b><a href="mailto://admin@minaw.net">admin@minaw.net</a></b>.</p>
    <p>If you wish to contact me for anything, use <b><a href="mailto://le@minaw.net">le@minaw.net</a></b>.</p>
    <h3></h3>
    </div>
  </div>
{% endblock content %}

portfolio/templates/portfolio/labs.html
{% extends "portfolio/base.html" %}

{% block content %}
  <div class="content work">
    <h2>Labs</h2>
    <h3>I've experiments to run...</h3>
    <p>Here you can find some small web applications I host on this server.</p>
    <p>They were mainly done for exercising or experimenting, but they may be able to occupy you for a few minutes.</p>
    <ul>
      <li><b><a href="{% url 'avatar:main' %}">Avatar</a></b> is a procedural geometric avatar generator. It was designed to provide guest profile pics on my blog. It features a basic request API and Disqus integration.</li>
      <li><b><a href="{% url 'dynimg:main' %}">DynImg</a></b> is a dynamic image linker. It basically links several pictures to one URL by randomly choosing one each time the URL is called.</li>
      <li><b><a href="{% url 'namegen:main' %}">NameGen</a></b> is a simple online fantasy name generator based on phonemes concatenation.</li>
      <li><b><a href="{% url 'quotes:main' %}">Quotes</a></b> is just a quotes app for fun.</li>
    </ul>
    <h3>...there is research to be done...</h3>
    <p>A few other projects are also hosted here, although they come out of the 'labs' category:</p>
    <ul>
      <li>The <b><a href="{% url 'profs:main' %}">ENSAPLV teachings exchange platform</a></b>, intended for students to share their advises on their teachings,</li>
      <li>The <b><a href="{% url 'profs:main' %}">Skywanderers registration app</a></b>, allowing <a href="http://www.skywanderersgame.com">Skywanderers</a> backers to redeem their rank on the game's official forums.</li>
    </ul>
    <h3>...on the people who are still alive!</h3>
    <p>You can also browse through various stuff on my <b><a href="https://github.com/LeMinaw">GitHub profile</a></b> if you have insomnia.</p>
  </div>
{% endblock content %}

portfolio/templates/portfolio/main.html
{% extends "portfolio/base.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block htmlparams %}
  class="noscroll"
{% endblock %}

{% block content %}
  <div class="title">
    <div id="name">
      <h1 class="{% if not work_cover.black_txt %}white{% endif %}">leminaw // renaud perrin</h1>
    </div>
  </div>

  <div class="wrapper">
    <div id="gallery" class="content">
      <div class="row">
        {% for work in works %}
          <div class="thumb">
            <div class="imgcontainer" style="{{ work.get_css_gradient }}">
              <a href="{{ work.get_absolute_url }}">
                {% thumbnail work.cover "300x300" crop="noop" as thumb %}
                  <img class="fade" src="{{ work.get_svg_placeholder }}" data-src="{{ thumb.url }}" alt="{{ work.title }}">
                {% endthumbnail %}

                <div class="legend">
                  <span>{{ work.title }}</span>
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="row"></div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'portfolio/js/scroll.js' %}"></script>
  <script src="{% static 'portfolio/js/gallery.js' %}"></script>
{% endblock scripts %}

portfolio/templates/portfolio/work.html
{% extends "portfolio/base.html" %}

{% load markup %}

{% block content %}
  <div id="work" class="content work">
    <h2>leminaw // renaud perrin :: {{ work.title }}</h2>
    <img src="{{ work.cover.url }}" alt="{{ work.title }}"/>
    <h3>{{ work.subtitle }}</h3>
    <span>{{ work.content|commonmark }}</span>

    <div class="categs">
      {% for w_categ in work_categs %}
        <a href="{{ w_categ.get_absolute_url }}">{{ w_categ.name }}</a>
      {% endfor %}
    </div>
  </div>
{% endblock content %}