avatar/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "avatar"
urlpatterns = [
    url(r'^$',                                          views.main,    name="main"),
    url(r'^about/?$',                                   views.about,   name="about"),
    url(r'^i/(?P<id_img>[0-9a-z]+)/(?P<size>[0-9]+)/?$', views.getimg,  name="getimg"),
    url(r'^i/(?P<id_img>[0-9a-z]+)/?$',                  views.getimg,  name="getimg"),
]

dynimg/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "dynimg"
urlpatterns = [
    url(r'^$',                       views.main,    name="main"),    # Start, end
    url(r'^about/?$',                views.about,   name="about"),   # Start, "about/", end
    url(r'^i/(?P<id_img>[0-9]+)/?$', views.getimg,  name="getimg"),  # Start, "i/", one ore more digits (id_img), "/", end
]

leminaw/urls.py
#-*- coding: utf-8 -*-

from django.conf             import settings
from django.conf.urls        import include, url
from django.conf.urls.static import static
from django.contrib          import admin
from perso.views             import create_error_view

urlpatterns = [
    url(r'^admin/',    admin.site.urls),
    url(r'^namegen/',  include("namegen.urls")),
    url(r'^dynimg/',   include("dynimg.urls")),
    url(r'^playel/',   include("playel.urls")),
    url(r'^profs/',    include("profs.urls")),
    url(r'^avatar/',   include("avatar.urls")),
    url(r'^quotes/',   include("quotes.urls")),
    url(r'^register/', include("register.urls")),
    url(r'^blog/',     include("perso.urls")),
    url(r'^',          include("portfolio.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

handler400 = create_error_view(code=400)
handler403 = create_error_view(code=403)
handler404 = create_error_view(code=404)
handler500 = create_error_view(code=500)

namegen/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "namegen"
urlpatterns = [
    url(r'^$',        views.main,  name="main"),  # Start, end
    url(r'^about/?$', views.about, name="about"), # Start, "about/", end
    url(r'^top/?$',   views.top,   name="top"),   # Start, "top/", end
    url(r'^l/$',      views.like,  name="like"),  # Start, "l/", end
]

perso/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "perso"
urlpatterns = [
    url(r'^$',                                                  views.main,        name='main'),
    url(r'^(?P<pageId>[0-9]+)/?$',                              views.main,        name='main'),
    url(r'^about/?$',                                           views.about,       name='about'),
    url(r'^contact/?$',                                         views.contact,     name='contact'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/?$',                    views.main,        name='main'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/(?P<pageId>[0-9]+)/?$', views.main,        name='main'),
    url(r'^publication/(?P<slug>[-a-zA-Z0-9_]+)/?$',            views.publication, name='publication'),
    url(r'^tag/(?P<slug>[-a-zA-Z0-9_]+)/?$',                    views.tag,         name='tag'),
]

profs/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "profs"
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^contact/?$', views.contact, name='contact'),
    url(r'^modules/?$', views.modules, name='modules'),
    url(r'^module/(?P<semester>[-a-zA-Z0-9_]+)/(?P<subject>[-a-zA-Z0-9_]+)/(?P<teacher>[-a-zA-Z0-9_]+)/?$', views.module, name='module'),
]

perso/models.py
#-*- coding: utf-8 -*-

from django.db   import models
from django.urls import reverse
from hashlib import md5

class Publication(models.Model):
    added    = models.DateTimeField(auto_now_add=True, verbose_name="ajouté")
    modif    = models.DateTimeField(auto_now=True    , verbose_name="modifié")
    slug     = models.SlugField()
    cover    = models.ForeignKey('Cover', null=True, blank=True, on_delete=models.CASCADE, verbose_name="couverture")
    title    = models.CharField(max_length=64,  verbose_name="titre")
    subtitle = models.CharField(max_length=128, blank=True, verbose_name="sous-titre")
    content  = models.TextField(blank=True,     verbose_name="contenu")
    abstract = models.TextField(blank=True,     verbose_name="résumé")
    pin      = models.BooleanField(default=False, verbose_name="épinglé")
    categ    = models.ForeignKey('Category', null=True, on_delete=models.CASCADE, verbose_name="catégorie")
    tags     = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('perso:publication', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "publication"
        ordering = ['-added']


class Category(models.Model):
    id    = models.AutoField(primary_key=True)
    descr = models.TextField(blank=True,    verbose_name="description")
    name  = models.CharField(max_length=64, verbose_name="nom")
    menu  = models.BooleanField(default=True)
    slug  = models.SlugField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('perso:main', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = "catégorie"
        ordering = ['menu', 'id']


class Tag(models.Model):
    name  = models.CharField(max_length=16, verbose_name="nom")
    slug  = models.SlugField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('perso:tag', kwargs={'slug': self.slug})

    def get_occurences(self):
        return self.publication_set.count()

    class Meta:
        verbose_name = "étiquette"


class Comment(models.Model):
    added   = models.DateTimeField(auto_now_add=True, verbose_name="ajouté")
    pseudo  = models.CharField(max_length=64)
    email   = models.EmailField(blank=True)
    content = models.TextField(verbose_name="contenu")
    publi   = models.ForeignKey('Publication', on_delete=models.CASCADE, verbose_name="publication")

    def __str__(self):
        return str(self.publi) + ' - ' + str(self.id)

    def get_absolute_url(self):
        return reverse('perso:tag', kwargs={'slug': self.slug})

    def get_avatar_url(self, size=90):
        if self.email != '':
            uid = md5(self.email.lower().encode()).hexdigest()
        else:
            uid = md5(self.pseudo.lower().encode()).hexdigest()
        return "https://www.gravatar.com/avatar/%(uid)s?s=%(size)s&d=http://minaw.net/avatar/i/%(uid)s/%(size)s" % {'uid':uid, 'size':size}

    class Meta:
        verbose_name = "commentaire"
        ordering = ['-added']


class Cover(models.Model):
    name  = models.CharField(max_length=64, verbose_name="nom")
    image = models.ImageField()
    descr = models.TextField(blank=True,    verbose_name="description")
    pin   = models.BooleanField(default=False, verbose_name="épinglé")
    blackOverlay = models.BooleanField(default=False, verbose_name="surimpression noire")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "couverture"


class Subscription(models.Model):
    added = models.DateTimeField(auto_now_add=True, verbose_name="ajouté")
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "souscription"

perso/forms.py
#-*- coding: utf-8 -*-

from django       import forms
from perso.models import *

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['email']
        error_messages = {
            'email': {
                'unique': "Cette adresse email est déjà enregistrée !"
            }
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['pseudo', 'email', 'content', 'publi']
        widgets = {'publi': forms.HiddenInput()}
        labels = {
            'pseudo': "Nom ou pseudo",
            'email': "Adresse e-mail (facultative)",
            'content': "Votre commentaire"
        }

perso/views.py
#-*- coding: utf-8 -*-

from django.core.paginator import Paginator
from django.shortcuts      import render, render_to_response
from django.template       import RequestContext
from django.http           import HttpResponse, HttpResponseRedirect, Http404
from random                import choice, sample
from math                  import ceil
from perso.forms           import *
from perso.models          import *


def nest(iterable, count):
    """Makes a list of lists of <count> elements out of an input <iterable>."""
    outLen = int(ceil(len(iterable) / count))
    return [iterable[i * count : (i+1) * count] for i in range(outLen)]

def page_contains(paginator, element):
    """Returns the first page of <paginator> containing <element>."""
    for page_nb in paginator.page_range:
        page = paginator.page(page_nb)
        if element in page.object_list:
            return page


def main(request, pageId=1, cat_slug=None):
    if cat_slug is None:
        publications = Publication.objects.filter(pin=True)
        coverImage = choice(Cover.objects.filter(pin=True))
    else:
        try:
            categ = Category.objects.get(slug=cat_slug)
        except Category.DoesNotExist:
            if request.path.endswith('/'): # It's possible that the user requested another app without the trailing slash (minaw.net/profs)
                raise Http404()
            else:
                return HttpResponseRedirect(request.get_full_path() + '/')

        publications = Publication.objects.filter(categ=categ)
        try:
            coverImage = choice(publications.exclude(cover=None).filter(cover__pin=True)).cover
        except IndexError:
            coverImage = choice(Cover.objects.filter(pin=True))

    barItems     = Category.objects.filter(menu=True)
    moreBarItems = Category.objects.filter(menu=False)

    paginator = Paginator(publications, 3)
    page = paginator.page(pageId)
    publications = page.object_list

    lastPublications = Publication.objects.all()[:5]

    catchSentence = choice([
        "Vous venez souvent ici ?",
        "Vous appréciez mon travail ?",
        "Vous aimeriez m'aider ?"]) + " " + choice([
        "Payez moi un café.",
        "Offrez moi une part de pizza froide.",
        "Remboursez l'eau de mes pâtes."])

    tags = sorted(Tag.objects.all(), key=lambda tag: tag.get_occurences())[:16]

    if Publication.objects.count() >= 4:
        randomPublications = sample(list(Publication.objects.all()), 4)
    else:
        randomPublications = Publication.objects.all()
    randomPublications = nest(randomPublications, 2)

    if "subscribe" in request.POST:
        subForm = SubscribeForm(request.POST)
        if subForm.is_valid():
            subForm.save()
    else:
        subForm = SubscribeForm()

    if "comment" in request.POST:
        comForm = CommentForm(request.POST)
        if comForm.is_valid():
            comForm.save()
    else:
        comForm = CommentForm()

    return render(request, "perso/main.html", locals())

def publication(request, slug):
    barItems     = Category.objects.filter(menu=True)
    moreBarItems = Category.objects.filter(menu=False)

    publication = Publication.objects.get(slug=slug)
    categ = publication.categ

    try:
        coverImage = choice(Publication.objects.filter(categ=categ).exclude(cover=None).filter(cover__pin=True)).cover
    except IndexError:
        coverImage = choice(Cover.objects.filter(pin=True))

    try:
        prev_pub = Publication.get_previous_by_added(publication)
    except Publication.DoesNotExist:
        prev_pub = None
    try:
        next_pub = Publication.get_next_by_added(publication)
    except Publication.DoesNotExist:
        next_pub = None

    if "comment" in request.POST:
        comForm = CommentForm(request.POST)
        if comForm.is_valid():
            comForm.save()
    else:
        comForm = CommentForm()

    return render(request, "perso/publi.html", locals())

def tag(request, slug):
    return render(request, "perso/tag.html", locals())

def about(request):
    barItems     = Category.objects.filter(menu=True)
    moreBarItems = Category.objects.filter(menu=False)

    coverImage = choice(Cover.objects.filter(pin=True))

    return render(request, "perso/about.html", locals())

def contact(request):
    barItems     = Category.objects.filter(menu=True)
    moreBarItems = Category.objects.filter(menu=False)

    coverImage = choice(Cover.objects.filter(pin=True))

    return render(request, "perso/contact.html", locals())


def create_error_view(code):
    def error_view(request, *args, **kwargs):
        barItems     = Category.objects.filter(menu=True)
        moreBarItems = Category.objects.filter(menu=False)

        coverImage = choice(Cover.objects.filter(pin=True))

        response = render(request, "perso/error.html", locals())
        response.status_code = code
        return response
    return error_view

perso/templates/perso/about.html
{% extends "perso/base.html" %}

{% block title %}
  À propos
{% endblock %}

{% block content %}
  <div class="w3-row w3-padding">
    <div class="w3-col l2 s12"><br/></div>
    <div class="w3-col l8 s12">
      <div class="w3-container w3-white w3-margin w3-padding-large">
        <h1>À propos</h1>
        <h2>Ma gueule</h2>
        <p>Je suis étudiant en architecture et ingénierie du bâtiment.<br/>Mais pas que...</p>
        <p>Je suis passionné d'arts et de techniques, et ce site à pour vocation d'accueillir mes divers travaux.<br/>J'essaie d'intégrer la machine à mon travail, et de lui faire faire ce qu'elle seule peut accomplir.</p>
        <p>Si vous voulez me contacter pour quoi que ce soit, vous pouvez le faire via l'<a href="{% url 'perso:contact' %}">onglet contact</a>.</p>
        <h2>Inspiration et admiration</h2>
        <ul class="w3-col l4 s12">
          <li>László Moholy-Nagy</li>
          <li>Steve Reich</li>
          <li>Yes</li>
        </ul>
        <ul class="w3-col l4 s12">
          <li>Constant Nieuwenhuys</li>
          <li>Wim Wenders</li>
          <li>Malevitch</li>
        </ul>
        <ul class="w3-col l4 s12">
          <li>Realmyop (Jemleglitch)</li>
          <li>Hanz Zimmer</li>
          <li>Des gens</li>
        </ul>
        <h2>À propos de ce site</h2>
        <p>Ce site est fièrement propulsé par le <a href="https://www.djangoproject.com/">framework Django</a>. Il utillise également <a href="https://www.w3schools.com/w3css/">w3.css</a> et <a href="https://jquery.com/">JQuery</a> (oui, je sais...) pour ce qui relève de l'affichage.</p>
        <p>Comme j'avais des besoins particuliers, je l'ai programmé moi même. Si ça vous intérersse, le <a href="https://github.com/LeMinaw/minaw.net">code source</a> est disponible sur <a href="https://github.com/LeMinaw/">mon GitHub</a>.</p>
      </div>
    </div>
  </div>
{% endblock content %}

perso/templates/perso/comment_list.html
{% load form_filters %}

{% for comment in publication.comment_set.all %}
  <div class="comment">
    <div class="w3-col l2 m3">
      <img class="avatar" src="{{ comment.get_avatar_url }}">
    </div>
    <div class="w3-col l10 m9">
      <h4>{{ comment.pseudo }} <span class="w3-opacity w3-medium">{{ comment.added }}</span></h4>
      <p>{{ comment.content }}</p>
    </div>
  </div>
{% empty %}
  <h6 class="w3-margin-top w3-center">Aucun commentaire pour le moment. :-(</h6>
{% endfor %}
<p class="w3-clear w3-margin-bottom"></p>
{% comment %}
<hr>
<h3>Ajoutez un commentaire !</h3>
<form action="" method="post">
  {% csrf_token %}
  <input type="hidden" name="{{ comForm.publi.html_name }}" value="{{ publication.id }}"/>
  <div class="w3-col l6 m12">
    <div class="w3-margin-right nomargin-small">
      {{ comForm.pseudo.label_tag }}
      {{ comForm.pseudo|addcss:'w3-input w3-border'}}
    </div>
  </div>
  <div class="w3-col l6 m12">
    <div class="w3-margin-left nomargin-small">
      {{ comForm.email.label_tag }}
      {{ comForm.email|addcss:'w3-input w3-border w3-margin-bottom'}}
    </div>
  </div>
  {{ comForm.content.label_tag }} {{ comForm.content|addcss:'w3-input w3-border w3-margin-bottom'}}
  <button name="comment" type="submit" class="w3-button w3-block w3-large w3-blue-gray">Envoyer <i class="fa fa-send-o"></i></button>
</form>
{% endcomment %}

perso/templates/perso/contact.html
{% extends "perso/base.html" %}

{% block title %}
  Contact
{% endblock %}

{% block content %}
  <div class="w3-row w3-padding">
    <div class="w3-col l2 s12"><br/></div>
    <div class="w3-col l8 s12">
      <div class="w3-container w3-white w3-margin w3-padding-large">
        <h1>Contact</h1>
        <h2>Vous avec une remarque ou une question concernant minaw.net ?</h3>
        <p>Faites en simplement part à l'adresse <a href="mailto://admin@minaw.net">admin@minaw.net</a>.</p>
        <h2>Vous désirez me contacter ?</h3>
        <p>Si, pour toute autre raison, vous désirez me contacter, vous pouvez le faire à l'adresse <a href="mailto://le@minaw.net">le@minaw.net</a>.</p>
      </div>
    </div>
  </div>
{% endblock content %}

perso/templates/perso/main.html
{% extends "perso/base.html" %}
{% load staticfiles %}

{% block title %}
  {{ categ.name|default:'Acceuil' }}
{% endblock %}

{% block content %}
  <div class="w3-row w3-padding">

    {% block entries %}
      <div class="w3-col l8 s12">

        {% for publication in publications %}
          <div class="w3-container w3-white w3-margin w3-padding-large">
            <div class="w3-center">
              <h3>{{ publication.title }}</h3>
              <h5>{{ publication.subtitle}}, <span class="w3-opacity">{{ publication.added }}</span></h5>
            </div>

            <div class="w3-justify">
              <img src="{{ publication.cover.image.url }}" class="w3-padding-16 fullwidth">
              <p>{{ publication.abstract|linebreaksbr }}</p>
              <p class="w3-left"><a href="{{ publication.get_absolute_url }}" class="w3-button w3-white w3-border">
                <b>Lire la suite...</b>
              </a></p>
              <p class="w3-right"><button class="w3-button w3-black" onclick="toggleComments('comments-{{ publication.slug }}')">
                <b>Commentaires &nbsp;</b> <span class="w3-tag w3-white">{{ publication.comment_set.count }}</span>
              </button></p>
              <p class="w3-clear"></p>
              <div class="comments w3-row w3-margin-bottom" id="comments-{{ publication.slug }}">
                <hr>
                {% include "perso/comment_list.html" %}
              </div>
            </div>
          </div>
          <hr>

        {% empty %}
        <div class="w3-container w3-white w3-margin w3-padding-large">
          <div class="w3-center">
            <h3>À VENIR !</h3>
            <p>Aucune publication dans la catégorie {{ categ }} pour le moment.</p>
            <h6 class="w3-margin-bottom w3-margin-top"><a href="{% url 'perso:main' %}" class="w3-button w3-block w3-large w3-blue-gray w3-text-white">RETOURNER À L'ACCUEIL</a></h6>
          </div>
        </div>

        {% endfor %}

        {% include "perso/pagination.html" %}
      </div>
    {% endblock entries %}

    {% block sidebar %}
      <div class="w3-col l4">
        {# About Card #}
        <div class="w3-white w3-margin">
          <img src="{% static 'perso/img/profile.jpg' %}" alt="LeMinaw" class="fullwidth">
          <div class="w3-container w3-black">
            <h4>Le minaw</h4>
            <p>Je suis un artiste contemporain visionnaire, adoptant une vision progressiste des systèmes de pensées qui nous entourent. J'adore me beurrer la biscote, et j'espère que vous aussi. Ceci étant je ne suis pas contre un peu de confiote.</p>
          </div>
        </div>
        <hr>

        {# Last posts #}
        <div class="w3-white w3-margin" id="lastPosts">
          <div class="w3-container w3-padding w3-black">
            <h4>Dernières publications</h4>
          </div>
          <ul class="w3-ul w3-hoverable w3-white">
            {% for publication in lastPublications %}
            <a href="{{ publication.get_absolute_url }}" class="w3-block">
              <li class="w3-padding-16 w3-border-top">
                  {% if publication.cover.image.url != None %}
                    <img src="{{ publication.cover.image.url }}" class="w3-left w3-margin-right"/>
                  {% endif %}
                  <span class="w3-large">{{ publication.title }}</span>
                  <br>
                  <span>{{ publication.subtitle }}</span>
                </li>
              </a>
            {% endfor %}
          </ul>
        </div>
        <hr>

        {# Donations #}
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Mécénat</h4>
          </div>
          <div class="w3-container w3-white">
            <p>{{ catchSentence }}</p>
            <h6 class="w3-margin-bottom w3-margin-top"><a href="http://paypal.me/leminaw" class="w3-button w3-block w3-large w3-blue-gray w3-text-white">FAIRE UN DON</a></h6>
          </div>
        </div>
        <hr>

        {# Tags #}
        <div class="w3-white w3-margin" id="tags">
          <div class="w3-container w3-padding w3-black">
            <h4>Étiquettes</h4>
          </div>
          <div class="w3-container w3-white">
            <p>
              {% for tag in tags %}
                <a href="{{ tag.get_absolute_url }}" class="w3-tag w3-light-grey w3-small w3-margin-bottom w3-hover-gray">{{ tag }}</a>
              {% endfor %}
            </p>
          </div>
        </div>
        <hr>

        {# Random #}
        <div class="w3-white w3-margin w3-hide-small" id="random">
          <div class="w3-container w3-padding w3-black">
            <h4>Au pif</h4>
          </div>
          <div class="w3-container w3-white">

            {% for column in randomPublications %}
              <div class="w3-margin-bottom w3-margin-top w3-col s6">
                {% for publication in column %}
                  <a href="{{ publication.get_absolute_url }}" class="w3-block w3-display-container w3-light-gray w3-hover-gray">
                    {% if publication.cover != None %}
                      <img src="{{ publication.cover.image.url }}" class="w3-hover-opacity">
                    {% else %}
                      <h6 class="w3-display-middle">{{ publication.title }}</h5>
                    {% endif %}
                  </a>
                {% endfor %}
              </div>
            {% endfor %}
          </div>
        </div>
        <hr>

        {# Other sites #}
        <div class="w3-white w3-margin" id="otherSites">
          <div class="w3-container w3-padding w3-black">
            <h4>Mes autres sites</h4>
          </div>
          <ul class="w3-ul w3-hoverable w3-white">
            <a href="{% url 'avatar:main' %}" class="w3-block">
              <li class="w3-padding-16 w3-border-top">
                  <span class="w3-large">Avatars</span>
                  <br>
                  <span>Un générateur procédural d'avatars.</span>
                </li>
              </a>
            <a href="{% url 'dynimg:main' %}" class="w3-block">
              <li class="w3-padding-16 w3-border-top">
                  <span class="w3-large">DynImg</span>
                  <br>
                  <span>Un générateur d'images dynamiques.</span>
                </li>
              </a>
            <a href="{% url 'namegen:main' %}" class="w3-block">
              <li class="w3-padding-16 w3-border-top">
                  <span class="w3-large">NameGen</span>
                  <br>
                  <span>Un générateur procédural de noms propres.</span>
                </li>
              </a>
            <a href="{% url 'profs:main' %}" class="w3-block">
              <li class="w3-padding-16 w3-border-top">
                  <span class="w3-large">Enseignements ENSAPLV</span>
                  <br>
                  <span>Un site d'avis sur les profs de l'ENSAPLV.</span>
                </li>
              </a>
          </ul>
        </div>
        <hr>

        {# Networks #}
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Restons connectés</h4>
          </div>
          <div class="w3-container w3-xlarge w3-padding">
            <a href="https://vimeo.com/leminaw">       <i class="fa fa-vimeo w3-hover-text-cyan"></i></a>
            <a href="https://soundcloud.com/leminaw">  <i class="fa fa-soundcloud w3-hover-text-orange"></i></a>
            <a href="https://plus.google.com/+LeMinaw"><i class="fa fa-google-plus w3-hover-text-red"></i></a>
            <a href="https://leminaw.bandcamp.com/">   <i class="fa fa-bandcamp w3-hover-text-cyan"></i></a>
            <a href="https://youtube.com/leminaw">     <i class="fa fa-youtube-play w3-hover-text-red"></i></a>
            <a href="https://github.com/LeMinaw">      <i class="fa fa-github w3-hover-text-cyan"></i></a>

          </div>
        </div>
        <hr>

        {# Subscribe #}
        <div id="subscribe" class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>S'abonner</h4>
          </div>
          <div class="w3-container w3-white">
            <p>Pour ne rien rater des nouveautés, abonnez vous à la newsletter.</p>
            <form action="#subscribe" method="post">
              {% csrf_token %}
              <p><input name="{{ subForm.email.html_name }}" class="w3-input w3-border" value="{{ subForm.email.value|default:'' }}" placeholder="Entrez votre email" style="width:100%" type="email" required id="{{ subForm.email.id_for_label }}"/></p>
              {{ subForm.email.errors }}
              <h6><button type="submit" class="w3-button w3-large w3-block w3-red" name="subscribe">S'ABONNER</button></h6>
            </form>
          </div>
        </div>
      </div>
    {% endblock sidebar %}
  </div>
{% endblock content %}

perso/templates/perso/navbar.html
{# This template needs population from barItems and moreBarItems #}

<div class="w3-top">
  <div class="w3-bar w3-black w3-card-2">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" onclick="toggleMenu()" title="Menu de navigation"><i class="fa fa-bars"></i></a>
    <a href="{% url 'perso:main' %}" class="w3-bar-item w3-button w3-padding-large">ACCUEIL</a>
    {% for barItem in barItems %}
      <a href="{{ barItem.get_absolute_url }}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">{{ barItem }}</a>
    {% endfor %}
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">Plus <i class="fa fa-caret-down" aria-hidden="true"></i></button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        {% for barItem in moreBarItems %}
          <a href="{{ barItem.get_absolute_url }}" class="w3-bar-item w3-button">{{ barItem }}</a>
        {% endfor %}
        <a href="{% url 'perso:about' %}" class="w3-bar-item w3-button">À propos</a>
        <a href="{% url 'perso:contact' %}" class="w3-bar-item w3-button">Contact</a>
      </div>
    </div>
    <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right"><i class="fa fa-search"></i></a>
  </div>
</div>

<div id="nav" class="w3-bar-block w3-black w3-hide-large w3-hide-medium w3-top">
  {% for barItem in barItems %}
    <a href="{{ barItem.get_absolute_url }}" class="w3-bar-item w3-button w3-padding-large">{{ barItem }}</a>
  {% endfor %}
</div>