leminaw/urls.py
#-*- coding: utf-8 -*-

from django.conf             import settings
from django.conf.urls        import include, url
from django.conf.urls.static import static
from django.contrib          import admin
from perso.views             import create_error_view

urlpatterns = [
    url(r'^admin/',    admin.site.urls),
    url(r'^namegen/',  include("namegen.urls")),
    url(r'^dynimg/',   include("dynimg.urls")),
    url(r'^playel/',   include("playel.urls")),
    url(r'^profs/',    include("profs.urls")),
    url(r'^avatar/',   include("avatar.urls")),
    url(r'^quotes/',   include("quotes.urls")),
    url(r'^register/', include("register.urls")),
    url(r'^blog/',     include("perso.urls")),
    url(r'^',          include("portfolio.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

handler400 = create_error_view(code=400)
handler403 = create_error_view(code=403)
handler404 = create_error_view(code=404)
handler500 = create_error_view(code=500)

perso/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "perso"
urlpatterns = [
    url(r'^$',                                                  views.main,        name='main'),
    url(r'^(?P<pageId>[0-9]+)/?$',                              views.main,        name='main'),
    url(r'^about/?$',                                           views.about,       name='about'),
    url(r'^contact/?$',                                         views.contact,     name='contact'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/?$',                    views.main,        name='main'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/(?P<pageId>[0-9]+)/?$', views.main,        name='main'),
    url(r'^publication/(?P<slug>[-a-zA-Z0-9_]+)/?$',            views.publication, name='publication'),
    url(r'^tag/(?P<slug>[-a-zA-Z0-9_]+)/?$',                    views.tag,         name='tag'),
]

profs/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "profs"
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^contact/?$', views.contact, name='contact'),
    url(r'^modules/?$', views.modules, name='modules'),
    url(r'^module/(?P<semester>[-a-zA-Z0-9_]+)/(?P<subject>[-a-zA-Z0-9_]+)/(?P<teacher>[-a-zA-Z0-9_]+)/?$', views.module, name='module'),
]

profs/models.py
#-*- coding: utf-8 -*-

from django.db   import models
from django.urls import reverse


class MainModel(models.Model):
    added = models.DateTimeField (auto_now_add=True, verbose_name="Ajouté")
    modif = models.DateTimeField (auto_now=True    , verbose_name="Modifié")

    class Meta:
        abstract = True


class Module(MainModel):
    content      = models.TextField      (            blank=True,               verbose_name="contenu")
    active       = models.BooleanField   (            default=True,             verbose_name="actif")
    semester     = models.ForeignKey     ('Semester', on_delete=models.CASCADE, verbose_name="semestre")
    subject      = models.ForeignKey     ('Subject',  on_delete=models.CASCADE, verbose_name="matière")
    teacher      = models.ForeignKey     ('Teacher',  on_delete=models.CASCADE, verbose_name="enseignant")

    def __str__(self):
        return self.semester.short + ' - ' + self.subject.short + ' - ' + self.teacher.short

    def get_absolute_url(self):
        return reverse('profs:module', kwargs={'semester': self.semester.slug, 'subject': self.subject.slug, 'teacher':self.teacher.slug})

    class Meta:
        verbose_name = "module"
        ordering = ['semester', 'subject', 'teacher']
        index_together = [
            ['semester', 'subject', 'teacher']
        ]


class Semester(MainModel):
    name  = models.CharField(max_length=16, verbose_name="nom")
    short = models.CharField(max_length=4,  verbose_name="nom abrégé")
    slug  = models.SlugField(               verbose_name="slug")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "semestre"


class Subject(MainModel):
    name  = models.CharField(max_length=32, verbose_name="nom")
    short = models.CharField(max_length=16, verbose_name="nom abrégé")
    slug  = models.SlugField(               verbose_name="slug")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "matière"


class Teacher(MainModel):
    name  = models.CharField(max_length=32, verbose_name="nom")
    short = models.CharField(max_length=16, verbose_name="nom abrégé")
    slug  = models.SlugField(               verbose_name="slug")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "enseignant"
        ordering = ['slug']


class Comment(MainModel):
    module    = models.ForeignKey               ('Module', related_name='comments', on_delete=models.CASCADE, verbose_name="module")
    content   = models.TextField                (                                                             verbose_name="contenu")
    author    = models.CharField                (max_length=32,                  default='',                  verbose_name="auteur")
    validated = models.BooleanField             (                                default=False,               verbose_name="validé")
    year      = models.PositiveSmallIntegerField(                                default=2016,                verbose_name="année") #TODO ranged YearField implementation

    def __str__(self):
        return str(self.module) + ' - ' + str(self.id)

    def get_absolute_url(self):
        return self.module.get_absolute_url()

    class Meta:
        verbose_name        = "avis"
        verbose_name_plural = "avis"

profs/forms.py
#-*- coding: utf-8 -*-

from django       import forms
from profs.models import *

class ModulesForm(forms.Form): #TODO Recode using ModelForm
    semester = forms.ModelChoiceField(required=False, label_suffix='', label="Semestre",   empty_label="Aucun", queryset=Semester.objects.all())
    subject  = forms.ModelChoiceField(required=False, label_suffix='', label="Matière",    empty_label="Aucun", queryset=Subject.objects.all())
    teacher  = forms.ModelChoiceField(required=False, label_suffix='', label="Enseignant", empty_label="Aucun", queryset=Teacher.objects.all())

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'author', 'year']
        labels     = {'author': "Nom ou pseudo",                          'year': "Année",                          'content': "Entrez votre message ici..."}
        help_texts = {'author': "C'est pas forcément votre vrai nom ;-)", 'year': "Quand avez vous eu ce module ?"}

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("label_suffix", "") # Removes label suffixes for all fields
        super(AddCommentForm, self).__init__(*args, **kwargs)

profs/views.py
#-*- coding: utf-8 -*-
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts             import render
from django.http                  import HttpResponse
from profs.processing             import *
from profs.models                 import *
from profs.forms                  import *


def main(request):
    return render(request, "profs/main.html", locals())


def about(request):
    return render(request, "profs/about.html", locals())


def contact(request):
    return render(request, "profs/contact.html", locals())


@csrf_exempt
# @vary_on_headers('HTTP_X_REQUESTED_WITH') # Needed when using caching
def modules(request):
    displayedModules = Module.objects.all()

    if request.method == "POST":
        form = ModulesForm(request.POST)
        if form.is_valid():
            semester = Semester.objects.filter(name=form.cleaned_data['semester']) or Semester.objects.all()
            subject  = Subject.objects.filter(name=form.cleaned_data['subject']) or Subject.objects.all()
            teacher  = Teacher.objects.filter(name=form.cleaned_data['teacher'])  or Teacher.objects.all()

            displayedModules = displayedModules.filter(semester__in=semester, subject__in=subject, teacher__in=teacher)

            if request.is_ajax():
                xmlResponse = Taconite()

                xmlResponse.show(".collection > a")
                hiddenModules = Module.objects.exclude(id__in=displayedModules)
                for module in hiddenModules:
                    xmlResponse.hide(".collection > a[href=\"" + module.get_absolute_url() + "\"]")

                for isemester in Semester.objects.all(): # TODO: Factorisation
                    result = Module.objects.filter(semester=isemester, subject__in=subject, teacher__in=teacher).exists()
                    xmlResponse.disable("#id_semester > [value=\"" + str(isemester.id) + "\"]", not result)

                for isubject in Subject.objects.all():
                    result = Module.objects.filter(semester__in=semester, subject=isubject, teacher__in=teacher).exists()
                    xmlResponse.disable("#id_subject > [value=\"" + str(isubject.id) + "\"]", not result)

                for iteacher in Teacher.objects.all():
                    result = Module.objects.filter(semester__in=semester, subject__in=subject, teacher=iteacher).exists()
                    xmlResponse.disable("#id_teacher > [value=\"" + str(iteacher.id) + "\"]", not result)

                xmlResponse.js("$(\"select\").material_select();")

                return HttpResponse(xmlResponse, content_type="text/xml")

    else:
        form = ModulesForm()

    return render(request, "profs/modules.html", locals())


@csrf_exempt
def module(request, semester, subject, teacher):
    semester = Semester.objects.get(slug=semester)
    subject  = Subject.objects.get(slug=subject)
    teacher  = Teacher.objects.get(slug=teacher)

    module = Module.objects.get(semester=semester, subject=subject, teacher=teacher)
    comments = module.comments.all().filter(validated=True)

    if request.method == "POST":
        form = AddCommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False) # form is a ModelForm
            new_comment.module = module
            new_comment.save()
            thanks = createThanks()
    else:
        form = AddCommentForm()

    return render(request, "profs/module.html", locals())

profs/templates/profs/about.html
{% extends "profs/base.html" %}

{% block title %}
    À propos
{% endblock %}

{% block header %}
    À propos...
{% endblock %}

{% block body %}
    <h2>Quelques précisions</h2>
    <h4>C'est quoi ce site ?</h4>
    <p class="flow-text">Normalement, tout est expliqué sur la <a href="{% url 'profs:main' %}">page d'acceuil</a>. <br/> C'est un projet personnel, lancé, géré et financé par un étudiant de l'ENSAPLV (c'est moi lol, ça va ?).</p>
    <h4>Pourquoi y'a les premières années ?</h4>
    <p class="flow-text">Parce qu'en général, ils aiment savoir à quelle sauce ils vont être mangés ! <br/> Inutile donc d'émettre de réels "avis" sur ces enseignements de première année. Préférez partager vos encouragements, et vos conseils avisés !</p>
    <h4>Pourquoi y'a pas les masters ?</h4>
    <p class="flow-text">Si quelqu'un veut bien m'expliquer comment ça se passe et me communiquer une liste des modules, ils y seront.</p>
    <h4>Avec quoi tu fais ça ?</h4>
    <p class="flow-text">Le backend est programmé en Python, à l'aide du framework Django. En plus d'utliser HTML5, CSS3 et JS, le frontend est basé sur le framework MaterializeCSS.</p>
    <h4>Pour terminer...</h4>
    <p class="flow-text">Ce site est une version en cours de développement. Si vous trouvez un bug, ou avez une idée d'amélioration, signalez le via l'<a href="{% url 'profs:contact' %}">onglet contact</a>.</p>
{% endblock %}

profs/templates/profs/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="fr-FR">

    <head>
        <meta charset="utf-8">
        <meta name="Author" content="LeMinaw">
        <meta name="Keywords" content="ensaplv,ensa,plv,enseignements,enseignants,profs,paris,la,villette,avis,commentaires">
        <meta name="Description" content="Un site indépedant regroupant l'avis des étudiants de l'ENSAPLV sur leurs modules d'enseignement.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css" type="text/css" media="screen,projection"/>
        <link rel="stylesheet" href="{% static 'profs/css/base.css' %}" type="text/css"/>
        <link rel="icon" href="favicon.ico" type="icon/png">

        {% include 'leminaw/analytics.html' %}

        <title>Enseignements de l'ENSAPLV | {% block title %}{% endblock %}</title>
    </head>

    <body>
        <header class="row">

            <div class="col s10 offset-s1 valign-wrapper">
                <h1 class="white-text">
                    <a href="" data-activates="slide-out" class="button-collapse hide-on-large-only">
                        <i class="left white-text material-icons medium">menu</i>
                    </a>
                    {% block header %}{% endblock %}
                </h1>
            </div>

            <ul id="slide-out" class="side-nav fixed">
                <br/>
                <li class="center-align"><img src="{% static 'profs/img/logo-ensa.png' %}" alt="Logo de l'ENSAPLV"/></li>
                <div class="container">
                    <li><a href="/profs" class="waves-effect">Accueil</a></li>
                    <li><a href="{% url 'profs:modules' %}" class="waves-effect">Enseignements</a></li>
                    <li><a href="{% url 'profs:about' %}" class="waves-effect">À propos</a></li>
                    <li><a href="{% url 'profs:contact' %}" class="waves-effect">Contact</a></li>
                </div>
            </ul>

        </header>

        <main><div class="row">
            <div class="col s10 offset-s1">
                {% block body %}{% endblock %}
            </div>
        </div></main>

        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
        <script type="text/javascript" src="{% static 'profs/js/base.js' %}"></script>
        <script type="text/javascript" src="{% static 'leminaw/js/taconite.min.js' %}"></script>
    </body>

</html>

profs/templates/profs/contact.html
{% extends "profs/base.html" %}

{% block title %}
    Contact
{% endblock %}

{% block header %}
    Contact
{% endblock %}

{% block body %}
    <h2>Pour toute remarque...</h2>
    <p class="flow-text">Pour toute suggestion ou remarque, envoyez simplement un mail à  l'adresse <a href="mailto:profs@minaw.net">profs@minaw.net</a>.</p>
    <p class="flow-text">Vous pouvez aussi envoyer vos sincères remerciments et félicitations, ça fait toujours plaisir !</p>
{% endblock %}

profs/templates/profs/main.html
{% extends "profs/base.html" %}

{% block title %}
    Accueil
{% endblock %}

{% block header %}
    Bienvenue.
{% endblock %}

{% block body %}
    <h2>Plateforme d'échange</h2>
    <p class="flow-text">L'accès à la plateforme a été suspendu. Pour plus d'informations à ce sujet, utilisez l'onglet Contact.</p>
    {% comment %}
    <p class="flow-text">Bienvenue sur la plate forme d'échanges inter-étudiants concernant les enseignements de l'ENSAPLV. <a href="{% url 'profs:modules' %}">Cliquez ici</a> pour commencer.</p>
    <h4>Super ! Qu'est ce que c'est ?</h2>
    <p class="flow-text">Ce site permet de consulter les programmes de différents modules d'enseignement, mais aussi de consulter et de lire des retours, des conseils ou des remarques d'étudiants concernants des enseignements particuliers.</p>
    <p class="flow-text">Vous pouvez bien évidemment y contribuer en faisant simplement part de vos retours.</p>
    <p class="flow-text">Une des principales vocations de ce site est l'assistance des étudiants dans leurs choix des modules d'enseignement.</p>
    <h4>C'est parti ! Gardez toutefois à l'esprit...</h3>
    <p class="flow-text">...que rien ne vaut le rapport humain : ce site n'est pas là pour remplacer les conversations que vous pourriez avoir avec des étudiants.</p>
    <p class="flow-text">...que ce site n'est pas officiel : c'est un travai personnel, aucunement rattaché à l'ENSAPLV.</p>
    <p class="flow-text">...qu'il est inutile de prendre ça trop à coeur : le tirage au sort est quand même très aléatoire !</p>
    {% endcomment %}
{% endblock %}

profs/templates/profs/module.html
{% extends "profs/base.html" %}

{% block title %}
    Module
{% endblock %}

{% block header %}
    Module
{% endblock %}

{% block body %}
    <h2>{{ module }}</h2>
    <p class="flow-text plvcolor-text">{{ module.semester }} <br/> {{ module.subject }} <br/> {{ module.teacher }}</p>

    <br/>
    <h4>Contenu du cours</h4>
    <p class="flow-text">{{ module.content|linebreaksbr }}</p>

    <br/>
    <h4>Commentaires d'étudiants</h4>
    {% comment %}
    {% for comment in comments %}
        <div class="card">
            <div class="card-content">
                <h5>{{ comment.author }} ({{ comment.year }})</h5>
                <p class="flow-text"> {{ comment.content|linebreaksbr }}</p>
            </div>
        </div>
    {% empty %}
        <p class="flow-text">Aucun commentaire pour le moment. :'(</p>
    {% endfor %}
    {% endcomment %}
    <p class="flow-text">L'accès aux commentaires est suspendu.</p>

    <br/>
    <h4>Partagez votre expérience !</h4>
    <div class="card">
        <div class="card-content">
            <form class="row" action="{% url 'profs:module' semester=semester.slug subject=subject.slug teacher=teacher.slug %}" method="post">
                {% csrf_token %}
                <div class="input-field col s12 m8">
                    <input id="{{ form.author.id_for_label }}" name="{{ form.author.name }}" type="text" value="{{ form.author.value }}" class=" validate">
                    <i class="tooltipped grey-text material-icons right" data-position="left" data-delay="50" data-tooltip="{{ form.author.help_text }}">info_outline</i>
                    {{ form.author.label_tag }}
                    {{ form.author.errors }}
                </div>


                <div class="input-field col s12 m4">
                    <input id="{{ form.year.id_for_label }}" name="{{ form.year.name }}" type="number" min="1950" max="2050" value="{{ form.year.value }}" class="validate">
                    <i class="tooltipped grey-text material-icons right" data-position="left" data-delay="50" data-tooltip="{{ form.year.help_text }}">info_outline</i>
                    {{ form.year.label_tag }}
                    {{ form.year.errors }}
                </div>
                <div class="input-field col s12">
                    <textarea id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" class="materialize-textarea validate"></textarea>
                    {{ form.content.label_tag }}
                    {{ form.content.errors }}
                </div>
                <div class="input-field col s12">
                    <button class="btn waves-effect waves-light" type="submit">Envoyer<i class="material-icons right">send</i></button>
                </div>
            </form>
        </div>
    </div>

    {% if thanks != None %}
        <div id="thanks" class="modal">
            <div class="modal-content">
                <h4>Merci pour ce retour !</h4>
                <p>{{ thanks }}</p>
            </div>
            <div class="modal-footer">
                <a class="modal-action modal-close waves-effect btn-flat">C'était un plaisir.</a>
            </div>
        </div>
    {% endif %}

    {% if not module.active %}
      <div id="inactive"></div>
    {% endif %}


{% endblock %}

profs/templates/profs/modules.html
{% extends "profs/base.html" %}

{% block title %}
    Enseignements
{% endblock %}

{% block header %}
    Enseignements
{% endblock %}

{% block body %}
    <h2>Liste des modules</h2>
    <p class="flow-text">L'accès à la plateforme a été suspendu. Pour plus d'informations à ce sujet, utilisez l'onglet Contact.</p>
    {% comment %}
    <form id="form" class="row" action="{% url 'profs:modules' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="input-field col s12 m4">
                {{ field.errors }}
                {{ field }}
                {{ field.label_tag }}
            </div>
        {% endfor %}
        <noscript>
            <div class="input-field col s12">
                <button class="btn waves-effect waves-light" type="submit">Envoyer<i class="material-icons right">send</i></button>
            </div>
        </noscript>
    </form>

    <div class="collection">
        {% for module in displayedModules %}
            <a href="{{ module.get_absolute_url }}" class="collection-item">{{ module }}
              {% if not module.active %}
                <span class="new badge" data-badge-caption="Archivé"></span>
              {% endif %}
            </a>
        {% empty %}
            <li class="collection-item">Aucun résultat trouvé. :'(</li>
        {% endfor %}
    </div>
    {% endcomment %}
{% endblock %}