dynimg/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "dynimg"
urlpatterns = [
    url(r'^$',                       views.main,    name="main"),    # Start, end
    url(r'^about/?$',                views.about,   name="about"),   # Start, "about/", end
    url(r'^i/(?P<id_img>[0-9]+)/?$', views.getimg,  name="getimg"),  # Start, "i/", one ore more digits (id_img), "/", end
]

leminaw/urls.py
#-*- coding: utf-8 -*-

from django.conf             import settings
from django.conf.urls        import include, url
from django.conf.urls.static import static
from django.contrib          import admin
from perso.views             import create_error_view

urlpatterns = [
    url(r'^admin/',    admin.site.urls),
    url(r'^namegen/',  include("namegen.urls")),
    url(r'^dynimg/',   include("dynimg.urls")),
    url(r'^playel/',   include("playel.urls")),
    url(r'^profs/',    include("profs.urls")),
    url(r'^avatar/',   include("avatar.urls")),
    url(r'^quotes/',   include("quotes.urls")),
    url(r'^register/', include("register.urls")),
    url(r'^blog/',     include("perso.urls")),
    url(r'^',          include("portfolio.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

handler400 = create_error_view(code=400)
handler403 = create_error_view(code=403)
handler404 = create_error_view(code=404)
handler500 = create_error_view(code=500)

perso/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = "perso"
urlpatterns = [
    url(r'^$',                                                  views.main,        name='main'),
    url(r'^(?P<pageId>[0-9]+)/?$',                              views.main,        name='main'),
    url(r'^about/?$',                                           views.about,       name='about'),
    url(r'^contact/?$',                                         views.contact,     name='contact'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/?$',                    views.main,        name='main'),
    url(r'^(?P<cat_slug>[-a-zA-Z0-9_]+)/(?P<pageId>[0-9]+)/?$', views.main,        name='main'),
    url(r'^publication/(?P<slug>[-a-zA-Z0-9_]+)/?$',            views.publication, name='publication'),
    url(r'^tag/(?P<slug>[-a-zA-Z0-9_]+)/?$',                    views.tag,         name='tag'),
]

dynimg/models.py
#-*- coding: utf-8 -*-

from django.urls import reverse
from django.db   import models
from datetime    import timedelta

class BaseModel(models.Model):
    created    = models.DateField    (auto_now_add=True,             verbose_name="création"             )
    last_used  = models.DateField    (auto_now=True,    blank=True,  verbose_name="dernière utilisation" )
    times_used = models.IntegerField (                  default=0,   verbose_name="nombre d'utilisations")

    class Meta:
        abstract = True


class ImageUrl(BaseModel):
    dwnlTime  = models.DurationField(default=timedelta(0),        verbose_name="temps de téléchargement")
    url       = models.URLField     (max_length=128, unique=True, verbose_name="URL"                    )

    def __str__(self):
        return self.url

    class Meta:
        verbose_name        = "URL d'image"
        verbose_name_plural = "URLs d'images"


class DynamicImg(BaseModel):
    name       = models.CharField      (max_length=32, blank=True, verbose_name="nom")
    urls       = models.ManyToManyField(ImageUrl,                  verbose_name="URLs")
    shadowMode = models.BooleanField   (default=False,             verbose_name="mode discret")

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('dynimg:getimg', kwargs={'id_img': self.id})

    def get_urls_nb(self):
        return self.urls.count()
    get_urls_nb.short_description = "Nombre d'URLs"


    class Meta:
        verbose_name        = "image dynamique"
        verbose_name_plural = "images dynamiques"

dynimg/forms.py
#-*- coding: utf-8 -*-

from django import forms

class NewImageForm(forms.Form): # TODO: Strong form validation, mind to reject URLs from DynImg to avoid endless loops !
    name       = forms.CharField    (required=False, label="Nom de l'image dynamique")
    urls       = forms.CharField    (required=True,  label="URLs des images (une URL par ligne)", widget=forms.Textarea)
    shadowMode = forms.BooleanField (required=False, label="Mode discret")

dynimg/views.py
#-*- coding: utf-8 -*-

from django.core.files.images import ImageFile
from django.core.files.temp   import NamedTemporaryFile
from django.shortcuts         import render
from django.http              import HttpResponse, HttpResponseRedirect
from django.db.models         import Sum
from urllib.request           import urlopen
from random                   import choice
from sys                      import exc_info
from re                       import search
from dynimg.models            import *
from dynimg.forms             import *
from dynimg.processing        import *

def main(request):
    if request.method == "POST":
        form = NewImageForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            urls = form.cleaned_data['urls'].splitlines()

            image = DynamicImg(name=name)
            image.save()
            for url in urls:
                url_obj = ImageUrl.objects.get_or_create(url=url)[0]
                image.urls.add(url_obj)
            image.save()

    else:
        form = NewImageForm()

    return render(request, "dynimg/main.html", locals())


def getimg(request, id_img):
    try:
        image = DynamicImg.objects.get(id=id_img)
    except:
        exception = search("'(.*)'", str(exc_info()[0])).group(1) # Ugly code to get exception name
        return imgHttpResponse(genErrImg(exception))

    image.times_used += 1
    image.save()
    imageUrl = choice(image.urls.all()) # Choosing an URL randomly from provided URLs list
    imageUrl.times_used += 1
    imageUrl.save()

    if image.shadowMode:
        try:
            imgtmp = NamedTemporaryFile(delete=True)
            imgtmp.write(urlopen(url).read())
            imgtmp.flush()
            img = ImageFile(imgtmp)
            return HttpResponse(img, content_type="image/jpeg") # Works with PNG
        except:
            exception = search("'(.*)'", str(exc_info()[0])).group(1) # Ugly code to get exception name
            return imgHttpResponse(genErrImg(exception))

    else:
        return HttpResponseRedirect(imageUrl.url)


def about(request):
    registeredImgs = DynamicImg.objects.count()
    registeredUrls = ImageUrl.objects.count()
    displayedImgs = DynamicImg.objects.aggregate(Sum('times_used'))['times_used__sum']

    return render(request, "dynimg/about.html", locals())

dynimg/templates/dynimg/about.html
{% extends "dynimg/base.html" %}

{% block title %} : À propos{% endblock %}

{% block content %}
  <h2>Qu'est-ce que DynImg ?</h2>
  <p>DynImg est un service gratuit permettant de lier plusieurs images à une seule adresse web. Quand un lien DynImg est chargé (par exemple par un autre site, blog, ou forum) ; une image aléatoire est tirée au sort parmi la liste que vous avez préalablement fournie.</p>
  <p>Ça peut être très utile pour faire une bannière web aléatoire facilement, ou pour afficher plusieurs déclinaisons d'un avatar ou d'une signature sur un forum, par exemple.</p>

  <h2>Comment ça marche ?</h2>
  <p>Rendez vous sur <a href="{% url "dynimg:main" %}">la page d'accueil</a>, remplissez la boîte avec des liens vers vos images statiques, et cliquez sur <i>C'est parti !</i>. Le site vous retournera un lien que vous pourrez utiliser comme d'habitude, sur des forums, des chats, ou sur vos designs web. Pas besoin de créer un compte, de fournir un email ou quoi que ce soit d'autre.</p>

  <h2>Est-ce que DynImg est un hébergeur d'images ?</h2>
  <p>Pas du tout ! DynImg fait juste le lien entre vos images statiques et votre lien DynImg unique. Vous devez héberger vos images par vos propres moyens, sur un service dédié.

  <h2>Qu'est-ce donc que le <i>mode discret</i> ?</h2>
  <p>Généralement, DynImg fonctionne très bien en mode par défaut. Dans le mode par défaut, DynImg procède à une simple redirection HTTP vers vos liens, à chaque chargement de voytre image dynamique.</p>
  <p>Parfois, vous pouvez avoir besoin de quelque chose de plus robuste ou de plus "caché". En mode discret, DynImg copiera les données internes de votre image en temps réel, pour les retourner sans procéder à une redirection. C'est plus lent et moins efficace, mais ça peut être utile dans certains cas.</p>

  <h2>Statistiques</h2>
  <p>Nous avons {{ registeredImgs }} images dynamiques enregistrées, liées à {{ registeredUrls }} adresses statiques.</p>
  <p>{{ displayedImgs }} images dynamiques ont été affichées par nos services.</p>

  <h2>Technologies utilisées</h2>
  <p>Cette application <i>open source</i> est programmée en Python, à l'aide du framework Django et du moteur PostgreSQL. L'affichage est réalisé à l'aide de HTML5 et de CSS3.</p>
{% endblock %}

dynimg/templates/dynimg/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-US">

<html>

  <head>
    <meta charset="utf-8">
    <meta name="Author" content="LeMinaw">
    <meta name="Keywords" content="dynamique,image,photo,aléatoire,dynimg,multiple,lien">
    <meta name="Description" content="Un site web pour générer des images dynamiques.">
    <link rel="icon" href="favicon.ico" type="icon/png">
    <link rel="stylesheet" href="{% static 'leminaw/css/minaw-css.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <title>DynImg</title>
  </head>

  <body>
    <header>
      <h1>DynImg{% block title %}{% endblock %}</h1>
    </header>
    <section id="content">
      {% block content %}{% endblock %}
    </section>
    <footer>
      <p>Une appli web par <a href="{% url "perso:main" %}">LeMinaw</a>.</p>
      <p>Licence CC BY-NC-SA 2.0</p>
      <p>- 2016 -</p>
    </footer>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
  </body>

</html>

dynimg/templates/dynimg/main.html
{% extends "dynimg/base.html" %}

{% block content %}
  <h2>Qu'est-ce que c'est ?</h2>
  <p>DynImg permets de lier plusieurs images à une seule adresse web. Quand un lien DynImg est chargé, une image aléatoire est tirée au sort parmi la liste que vous avez préalablement fournie.</p>
  <p>Ça peut être très utile pour faire une bannière web aléatoire facilement, ou pour afficher plusieurs déclinaisons d'un avatar ou d'une signature sur un forum.</p>
  <p>Pour plus d'informations, rendez vous sur la page <a href="{% url 'dynimg:about' %}">à propos</a>.</p>
  {% if image == None %}
    <h2>Créez votre image dynamique dès maintenant !</h2>
    <p>Suivez simplement les étapes ci dessous.</p>
    <form action="{% url 'dynimg:main' %}" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div>
          {{ field }}
          {{ field.label_tag }} {# Reversed to allow css "+" selection #}
        </div>
        {{ field.errors }}
        <br>
      {% endfor %}
      {{ form.non_field_errors }}
      <input type="submit" value="C'est parti !" />
    </form>
  {% else %}
    <h2>Succès !</h2>
    <p>Voici le lien vers votre image dynamique. Utilisez le simplement comme un lien ordinaire.</p>
    <code>{{ request.get_host }}{{ image.get_absolute_url }}</code>
    <p>Merci !</p>
  {% endif %}
{% endblock %}